// *****PLEASE ENTER YOUR DETAILS BELOW*****
// T6-rm-mongo.mongodb.js

// Student ID:33878897
// Student Name: Muhammad Mubashir Shah

// Comments for your marker:

// ===================================================================================
// DO NOT modify or remove any of the comments below (items marked with //)
// ===================================================================================

// Use (connect to) your database - you MUST update xyz001
// with your authcate username

use("msha0166");

// (b)
// PLEASE PLACE REQUIRED MONGODB COMMAND TO CREATE THE COLLECTION HERE
// YOU MAY PICK ANY COLLECTION NAME
// ENSURE that your query is formatted and has a semicolon
// (;) at the end of this answer

// Drop collection
db.teamdata.drop();

// Create collection and insert documents

// Insert all JSON documents generated by T6-rm-json.sql here.
const docs = [
  {
    "_id": 1,
    "carn_name": "RM Spring Series Clayton 2024",
    "carn_date": "22-Sep-2024",
    "team_name": "SunRunners",
    "team_leader": {
      "name": "Alice Wang",
      "phone": "0400123456",
      "email": "alice.wang@example.com"
    },
    "team_no_of_members": 0,
    "team_members": [
      {
        "competitor_name": null,
        "competitor_phone": null,
        "event_type": null,
        "entry_no": null,
        "starttime": "-",
        "finishtime": "-",
        "elapsedtime": "-"
      }
    ]
  },
  {
    "_id": 2,
    "carn_name": "RM Spring Series Clayton 2024",
    "carn_date": "22-Sep-2024",
    "team_name": "Speedsters",
    "team_leader": {
      "name": "Carol Ng",
      "phone": "0420123456",
      "email": "carol.ng@example.com"
    },
    "team_no_of_members": 0,
    "team_members": [
      {
        "competitor_name": null,
        "competitor_phone": null,
        "event_type": null,
        "entry_no": null,
        "starttime": "-",
        "finishtime": "-",
        "elapsedtime": "-"
      }
    ]
  },
  {
    "_id": 3,
    "carn_name": "RM Spring Series Caulfield 2024",
    "carn_date": "05-Oct-2024",
    "team_name": "Speedsters",
    "team_leader": {
      "name": "Henry Li",
      "phone": "0470123456",
      "email": "henry.li@example.com"
    },
    "team_no_of_members": 0,
    "team_members": [
      {
        "competitor_name": null,
        "competitor_phone": null,
        "event_type": null,
        "entry_no": null,
        "starttime": "-",
        "finishtime": "-",
        "elapsedtime": "-"
      }
    ]
  },
  {
    "_id": 4,
    "carn_name": "RM Summer Series Caulfield 2025",
    "carn_date": "02-Feb-2025",
    "team_name": "Marathoners",
    "team_leader": {
      "name": "Paul White",
      "phone": "0540123456",
      "email": "paul.white@example.com"
    },
    "team_no_of_members": 0,
    "team_members": [
      {
        "competitor_name": null,
        "competitor_phone": null,
        "event_type": null,
        "entry_no": null,
        "starttime": "-",
        "finishtime": "-",
        "elapsedtime": "-"
      }
    ]
  },
  {
    "_id": 5,
    "carn_name": "RM Autumn Series Clayton 2025",
    "carn_date": "15-Mar-2025",
    "team_name": "Champions",
    "team_leader": {
      "name": "Alice Wang",
      "phone": "0400123456",
      "email": "alice.wang@example.com"
    },
    "team_no_of_members": 0,
    "team_members": [
      {
        "competitor_name": null,
        "competitor_phone": null,
        "event_type": null,
        "entry_no": null,
        "starttime": "-",
        "finishtime": "-",
        "elapsedtime": "-"
      }
    ]
  },
  {
    "_id": 105,
    "carn_name": "RM Winter Series Caulfield 2025",
    "carn_date": "29-Jun-2025",
    "team_name": "Test Team",
    "team_leader": {
      "name": "Keith Rose",
      "phone": "0422141112",
      "email": "keith.rose@student.monash.edu"
    },
    "team_no_of_members": 1,
    "team_members": [
      {
        "competitor_name": "Keith Rose",
        "competitor_phone": "0422141112",
        "event_type": "5 Km Run",
        "entry_no": 5,
        "starttime": "-",
        "finishtime": "-",
        "elapsedtime": "-"
      }
    ]
  }
];
db.teamdata.insertMany(docs);

// List all documents you added
db.teamdata.find().pretty();

// (c)
// PLEASE PLACE REQUIRED MONGODB COMMAND/S FOR THIS PART HERE
// ENSURE that your query is formatted and has a semicolon
// (;) at the end of this answer

// List carnival date, carnival name, team name, and team leader’s name
// for any team with at least one member whose event_type is "5 Km Run" or "10 Km Run".
db.teamdata
  .find(
    { event_type: { $in: ["5 Km Run", "10 Km Run"] } },
    { _id: 0, carn_date: 1, carn_name: 1, team_name: 1, team_leader: 1 }
  )
  .pretty();

// (d)
// PLEASE PLACE REQUIRED MONGODB COMMAND/S FOR THIS PART HERE
// ENSURE that your query is formatted and has a semicolon
// (;) at the end of this answer

// (i) Add new team
db.teamdata.insertOne({
  "_id": 999, // choose an unused _id
  "carn_name": "RM Winter Series Caulfield 2025",
  "carn_date": "29-Jun-2025",
  "team_name": "The Great Runners",
  "team_leader": "Jackson Bull",
  "leader_phone": "0422412524",
  "leader_email": "jackson.bull@student.monash.edu",
  "competitor_name": "Jackson Bull",
  "competitor_phone": "0422412524",
  "event_type": "5 Km Run",
  "entry_no": 500, // your chosen entry_no
  "starttime": "-",
  "finishtime": "-",
  "elapsedtime": "-"
});

// Illustrate/confirm changes made
db.teamdata.find({ team_name: "The Great Runners" }).pretty();

// (ii) Add new team member
db.teamdata.insertOne({
  "_id": 1000,
  "carn_name": "RM Winter Series Caulfield 2025",
  "carn_date": "29-Jun-2025",
  "team_name": "The Great Runners",
  "team_leader": "Jackson Bull",
  "leader_phone": "0422412524",
  "leader_email": "jackson.bull@student.monash.edu",
  "competitor_name": "Steve Bull",
  "competitor_phone": "0422251427",
  "event_type": "10 Km Run",
  "entry_no": 501,
  "starttime": "-",
  "finishtime": "-",
  "elapsedtime": "-"
});

// Illustrate/confirm changes made
db.teamdata.find({ team_name: "The Great Runners" }).pretty();
