-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-02 21:03:48 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo ON
SPOOL oo_schema_output.txt

-- Student ID: 33878897
-- Student Name: Muhammad Mubashir Shah

DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE COUNTRY CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE_PORT_VISIT CASCADE CONSTRAINTS 
;

DROP TABLE MANIFEST CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE PORT CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE CABIN 
    ( 
     cabin_id                NUMBER (7)  NOT NULL , 
     cabin_number            VARCHAR2 (10)  NOT NULL , 
     ship_code               VARCHAR2 (10)  NOT NULL , 
     cabin_sleeping_capacity NUMBER (2)  NOT NULL , 
     cabin_class             CHAR (1)  NOT NULL 
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT check_cabin_class 
    CHECK (cabin_class IN ('B', 'I', 'O', 'S')) 
;

COMMENT ON COLUMN CABIN.cabin_id IS 'Cabin id (surrogate key)' 
;

COMMENT ON COLUMN CABIN.cabin_number IS 'Cabin number' 
;

COMMENT ON COLUMN CABIN.ship_code IS 'ships code' 
;

COMMENT ON COLUMN CABIN.cabin_sleeping_capacity IS 'cabin sleep capacity' 
;

COMMENT ON COLUMN CABIN.cabin_class IS 'Cabins class - Interior, Ocean view, Balcony, Suite
Possible values(I, O, B, S)
' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_id ) ;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_UQ UNIQUE ( cabin_number , ship_code ) ;

CREATE TABLE COUNTRY 
    ( 
     country_code CHAR (3)  NOT NULL , 
     country_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COUNTRY.country_code IS 'countries code' 
;

COMMENT ON COLUMN COUNTRY.country_name IS 'name of country' 
;

ALTER TABLE COUNTRY 
    ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( country_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id              VARCHAR2 (10)  NOT NULL , 
     cruise_departure_date  DATE  NOT NULL , 
     cruise_departure_time  DATE  NOT NULL , 
     cruise_name            VARCHAR2 (50)  NOT NULL , 
     cruise_description     VARCHAR2 (100)  NOT NULL , 
     cruise_cost_per_person NUMBER (10,2)  NOT NULL , 
     ship_code              VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'cruise id' 
;

COMMENT ON COLUMN CRUISE.cruise_departure_date IS 'cruise departure date' 
;

COMMENT ON COLUMN CRUISE.cruise_departure_time IS 'cruise departure times' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'cruise name' 
;

COMMENT ON COLUMN CRUISE.cruise_description IS 'cruise description' 
;

COMMENT ON COLUMN CRUISE.cruise_cost_per_person IS 'the cost of a cruise per person' 
;

COMMENT ON COLUMN CRUISE.ship_code IS 'ships code' 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE CRUISE_PORT_VISIT 
    ( 
     visit_id          NUMBER (7)  NOT NULL , 
     departure_arrival CHAR (1)  NOT NULL , 
     cruise_id         VARCHAR2 (10)  NOT NULL , 
     datetime          DATE , 
     port_code         CHAR (5)  NOT NULL 
    ) 
;

ALTER TABLE CRUISE_PORT_VISIT 
    ADD CONSTRAINT check_departure_arrival 
    CHECK (departure_arrival IN ('A', 'D')) 
;

COMMENT ON COLUMN CRUISE_PORT_VISIT.visit_id IS 'visit id (surrogate key)' 
;

COMMENT ON COLUMN CRUISE_PORT_VISIT.departure_arrival IS 'departure and arrival' 
;

COMMENT ON COLUMN CRUISE_PORT_VISIT.cruise_id IS 'cruise id' 
;

COMMENT ON COLUMN CRUISE_PORT_VISIT.datetime IS 'date and time' 
;

COMMENT ON COLUMN CRUISE_PORT_VISIT.port_code IS 'port code' 
;

ALTER TABLE CRUISE_PORT_VISIT 
    ADD CONSTRAINT CRUISE_PORT_VISIT_PK PRIMARY KEY ( visit_id ) ;

ALTER TABLE CRUISE_PORT_VISIT 
    ADD CONSTRAINT VISIT_UQ UNIQUE ( departure_arrival , cruise_id , datetime , port_code ) ;

CREATE TABLE MANIFEST 
    ( 
     manifest_id            NUMBER (7)  NOT NULL , 
     cruise_id              VARCHAR2 (10)  NOT NULL , 
     passenger_id           VARCHAR2 (10)  NOT NULL , 
     manifest_boarding_time DATE  NOT NULL , 
     cabin_id               NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN MANIFEST.manifest_id IS 'manifest identifyier (surrogate key)' 
;

COMMENT ON COLUMN MANIFEST.cruise_id IS 'cruise id' 
;

COMMENT ON COLUMN MANIFEST.passenger_id IS 'passenger id' 
;

COMMENT ON COLUMN MANIFEST.manifest_boarding_time IS 'manifest boarding time' 
;

COMMENT ON COLUMN MANIFEST.cabin_id IS 'Cabin id (surrogate key)' 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT MANIFEST_PK PRIMARY KEY ( manifest_id ) ;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT MANIFEST_UQ UNIQUE ( passenger_id , cruise_id ) ;

CREATE TABLE OPERATOR 
    ( 
     operator_id           VARCHAR2 (10)  NOT NULL , 
     operator_company_name VARCHAR2 (50)  NOT NULL , 
     operator_ceo_name     VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OPERATOR.operator_id IS 'operator id' 
;

COMMENT ON COLUMN OPERATOR.operator_company_name IS 'operator company name' 
;

COMMENT ON COLUMN OPERATOR.operator_ceo_name IS 'operator ceo name' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( operator_id ) ;

CREATE TABLE PASSENGER 
    ( 
     passenger_id            VARCHAR2 (10)  NOT NULL , 
     passenger_first_name    VARCHAR2 (50)  NOT NULL , 
     passenger_last_name     VARCHAR2 (50)  NOT NULL , 
     passenger_gender        VARCHAR2 (10)  NOT NULL , 
     passenger_dob           DATE  NOT NULL , 
     passenger_street        VARCHAR2 (100)  NOT NULL , 
     passenger_town          VARCHAR2 (50)  NOT NULL , 
     passenger_postcode      CHAR (10)  NOT NULL , 
     passenger_country       VARCHAR2 (50)  NOT NULL , 
     passenger_contact_phone VARCHAR2 (15) , 
     passenger_id1           VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PASSENGER.passenger_id IS 'passenger id' 
;

COMMENT ON COLUMN PASSENGER.passenger_first_name IS 'passengers first name' 
;

COMMENT ON COLUMN PASSENGER.passenger_last_name IS 'passengers last name' 
;

COMMENT ON COLUMN PASSENGER.passenger_gender IS 'passengers gender' 
;

COMMENT ON COLUMN PASSENGER.passenger_dob IS 'passenger date of birth' 
;

COMMENT ON COLUMN PASSENGER.passenger_street IS 'passengers street address' 
;

COMMENT ON COLUMN PASSENGER.passenger_town IS 'passengers town or city' 
;

COMMENT ON COLUMN PASSENGER.passenger_postcode IS 'passengers postcode' 
;

COMMENT ON COLUMN PASSENGER.passenger_country IS 'passengers country' 
;

COMMENT ON COLUMN PASSENGER.passenger_contact_phone IS 'passengers contact phone number' 
;

COMMENT ON COLUMN PASSENGER.passenger_id1 IS 'passenger id' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( passenger_id ) ;

CREATE TABLE PORT 
    ( 
     port_code      CHAR (5)  NOT NULL , 
     port_name      VARCHAR2 (50)  NOT NULL , 
     port_latitude  NUMBER (9,6)  NOT NULL , 
     port_longitude NUMBER (9,6)  NOT NULL , 
     country_code   CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PORT.port_code IS 'port code' 
;

COMMENT ON COLUMN PORT.port_name IS 'port name' 
;

COMMENT ON COLUMN PORT.port_latitude IS 'port latitude' 
;

COMMENT ON COLUMN PORT.port_longitude IS 'port longitude' 
;

COMMENT ON COLUMN PORT.country_code IS 'countries code' 
;

ALTER TABLE PORT 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( port_code ) ;

CREATE TABLE SHIP 
    ( 
     ship_code               VARCHAR2 (10)  NOT NULL , 
     ship_name               VARCHAR2 (50)  NOT NULL , 
     ship_commision_date     DATE  NOT NULL , 
     ship_tonnage            NUMBER (8)  NOT NULL , 
     ship_max_capacity       NUMBER (4)  NOT NULL , 
     ship_registered_country VARCHAR2 (50)  NOT NULL , 
     operator_id             VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_code IS 'ships code' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'ships name' 
;

COMMENT ON COLUMN SHIP.ship_commision_date IS 'ships commision date' 
;

COMMENT ON COLUMN SHIP.ship_tonnage IS 'ship weight' 
;

COMMENT ON COLUMN SHIP.ship_max_capacity IS 'ships max capacity' 
;

COMMENT ON COLUMN SHIP.ship_registered_country IS 'ships registered country' 
;

COMMENT ON COLUMN SHIP.operator_id IS 'operator id' 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_code ) ;

ALTER TABLE PORT 
    ADD CONSTRAINT country_port_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cruise_manifest_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT cruise_ship_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

ALTER TABLE CRUISE_PORT_VISIT 
    ADD CONSTRAINT cruise_visit_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT manifest_cabin_fk FOREIGN KEY 
    ( 
     cabin_id
    ) 
    REFERENCES CABIN 
    ( 
     cabin_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT operator_ship_fk FOREIGN KEY 
    ( 
     operator_id
    ) 
    REFERENCES OPERATOR 
    ( 
     operator_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT passenger_gardian_minor_fk FOREIGN KEY 
    ( 
     passenger_id1
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT passenger_manifest_fk FOREIGN KEY 
    ( 
     passenger_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE CRUISE_PORT_VISIT 
    ADD CONSTRAINT port_visit_fk FOREIGN KEY 
    ( 
     port_code
    ) 
    REFERENCES PORT 
    ( 
     port_code
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT ship_cabin_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             24
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
set echo OFF
SPOOL OFF